spring:
    jackson:
        serialization:
            write-dates-as-timestamps: false
    datasource:
        url: jdbc:mysql://localhost:3306/hrp?autoReconnect=true&useSSL=false&serverTimezone=Europe/Bucharest
        username: root
        password: password
        initialization-mode: never
        platform: mysql
        driver-class-name: com.mysql.jdbc.Driver
    batch:
        initialize-schema: never
    jpa:
        properties:
            hibernate:
                dialect: ro.appbranch.HRPortal.config.AppMysql5Dialect
                storage_engine: innodb
        hibernate:
            ddl-auto: none
    redis:
        host: localhost
        port: 6379
        database: 6
    session:
        store-type: redis
        timeout: 86400
        redis:
            flush-mode: on_save
            namespace: spring:session
    servlet:
        multipart:
            maxFileSize: 15MB
            maxRequestSize: 15MB
server:
    port: 8001
    error:
        whitelabel:
            enabled: false
logging:
    level:
        root: info
        org.springframework.orm.jpa.JpaTransactionManager: debug

